### ISSUE TITLE
$defaultMaxIter definition missing

### ISSUE THREAD

**Issue by szhorvat** [WolframResearch/FEMAddOns#7]
It seems that in a commit made after the last release, the definition of `$defaultMaxIter` in `FEMUtils.m` went missing.  This symbol is still being used here:

https://github.com/WolframResearch/FEMAddOns/blob/master/FEMAddOns/FEMUtils/Kernel/FEMUtils.m#L25

Offending commit:

https://github.com/WolframResearch/FEMAddOns/commit/10e6ee36d0cee87b6d3a35b15edd741eb5db2cb5#diff-7cc193883d597f26a74caa3caa6d7e17L25

I noticed this while browsing the sources using [the IDEA Wolfram Language plugin](http://wlplugin.halirutan.de), which warns about missing definitions.

**Comment by ruebenko** [comment]
Thanks a lot! Fixed with commit 7522a5ec1994727a8080d472740bc95f3c8c7f1c
